# RANDOM WALLETS MODE
RANDOM_WALLET = True  # True or False

# SLEEP MODE
IS_SLEEP = True  # True or False

SLEEP_FROM = 5  # Second
SLEEP_TO = 8  # Second

# PROXY MODE
USE_PROXY = False

# GWEI CONTROL MODE
CHECK_GWEI = True  # True or False
MAX_GWEI = 20

GAS_MULTIPLIER = 1

# RETRY MODE
RETRY_COUNT = 3

# INCH API KEY
INCH_API_KEY = "FZeIXlOPfCF94FsGLA4U03fX73IYlkvE"
